#!/usr/bin/env bash
#Display information on domains and sub-domains


print_domain() {
	echo "The subdomain www is a A record and points to 34.227.93.60"
	echo "The subdomain lb-01 is a A record and points to 34.227.93.60"
	echo "The subdomain web-01 is a A record and points to 54.197.94.136"
	echo "The subdomain web-02 is a A record and points to 18.204.10.0"
	}

if [ "$#" -eq 1 ]; then
	print_domain
fi

if [ "$(echo "$@" | awk '{print NF}')" -eq 2 ]; then
	if [ "$2" == "www" ] || [ "$2" == "lb-01" ]; then
		echo "The subdomain $2 is a A record and points to 34.227.93.60"
	elif [ "$2"  == "web-01" ]; then
		echo "The subdomain web-01 is a A record and points to 54.197.94.136"
	elif [ "$2" == "web-02" ]; then
		"The subdomain web-02 is a A record and points to 18.204.10.0"
	fi
fi
