#!/usr/bin/env bash
#Install and configure load balancer

sudo apt update

sudo apt install -y haproxy

cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 34.224.83.243:80 check
    server web-02 35.153.67.53:80 check
EOF


echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
