#!/usr/bin/env bash
#ping an ip address passed as an argument

if [ "$#" -eq 0 ]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi

if [ "$#" -gt 0 ]; then
	for ((i=1; i<=5; i++)); do
		ping "$1"
	done
fi
