#!/usr/bin/env bash
#script to loop infinitely and handle sigterm

function handle_signal() {
	echo "I am invincible!!!"
}

trap handle_signal SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
