#!/usr/bin/env bash
#Script to display numbers with message
i=1

while [ $i -le 20 ]; do
	echo "$i"
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad lauck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		*)
			;;
	esac
	((i++))
done
