#!/usr/bin/env bash
#Script to give information on school file

file='cat school'

if $file -e; then
	echo "school file exists"
	if [ -z "$file" ]; then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi

	if [ -f "$file" ]; then
		echo "school is a regular file"
	else
		:
	fi
else
	echo "school file does not exist"

fi
