#!/usr/bin/env bash
#Configure Nginx to run as nginx user

sudo useradd -r -s /bin/bash nginx
sudo chown -R nginx:nginx /etc/nginx
sudo sed -i "s/user.*/user nginx;/" /etc/nginx/nginx.conf
sudo service nginx reload
